### ISSUE TITLE
algorithm_statistic_unary_min_test sometimes fails

### ISSUE THREAD

**Issue by OliverSchmitz** [geoneric/fern#63]
Sometimes one of the unit test hangs, happened on macOS, debug build, static and libs

$ ctest -j8 --timeout 20
...
102/103 Test #100: feature_core_masked_array_test .....................   Passed    0.11 sec
103/103 Test  #74: algorithm_statistic_unary_min_test .................***Timeout  20.03 sec

99% tests passed, 1 tests failed out of 103

Total Test time (real) =  20.42 sec

**Comment by kordejong** [comment]
Should work now
